[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.backends._legacy:_Backend"

[project]
name = "notes-app-backend"
version = "0.1.0"
dependencies = [
    "fastapi>=0.109.0",
    "uvicorn[standard]>=0.27.0",
    "pydantic[dotenv]>=2.7.0",
    "python-dotenv>=1.0.0",
    "sqlmodel>=0.0.11",
]

[project.scripts]
start = "uvicorn.app.main:app"

[tool.black]
line-length = 88

[tool.isort]
profile = "black"